### ISSUE TITLE
Migrate to netwerk-digitaal-erfgoed org

### ISSUE THREAD

**Issue by ddeboer** [valevo/SABIO#10]
We already moved Werners UI to https://github.com/netwerk-digitaal-erfgoed/sabio-frontend.

I forked this repository to https://github.com/netwerk-digitaal-erfgoed/sabio-backend to be able to deploy to our infrastructure on code changes.

@valevo Please let me know if you’re okay with continuing work at https://github.com/netwerk-digitaal-erfgoed/sabio-backend, in which case I’ll grant you admin rights there. If you prefer to continue work here, I can periodically sync our fork.

**Comment by valevo** [comment]
As I said before somewhere, I prefer f the repo stays where it is.
I'll make changes in bulk, infrequently and with announcement.

**Comment by ddeboer** [comment]
Sounds good to me. When we sync your changes, they will automatically pushed to https://sabio.netwerkdigitaalerfgoed.nl.
